version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOSTNAME: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_PASSWORD: "arsalan@512"
      DATABASE_NAME: "fastapi"
      DATABASE_USERNAME: "postgres"
      SECRET_KEY: "13qidifru3u103djd"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "60"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "arsalan@512"
      POSTGRES_DB: "fastapi"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: